CREATE TABLE Person(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR (100) NOT NULL,
                       age INT,
                       email VARCHAR (100)
);

INSERT INTO Person(name, age, email) VALUES ('Tom', 25, 'tom@gmail.com');
INSERT INTO Person(name, age, email) VALUES ('Bob', 51, 'bob@gmail.com');
INSERT INTO Person(name, age, email) VALUES ('Katy', 38, 'katy@gmail.com');

ALTER TABLE Person ADD COLUMN created_at TIMESTAMP,
                   ADD COLUMN updated_at TIMESTAMP,
                   ADD COLUMN created_who VARCHAR;